name: Video Idea
description: Suggest an Episode for Genius Lounge's YouTube Channel
title: "[Video Idea]: "
labels: [video idea]
assignees:
  - trtmn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: "What's your github username in case we need to get ahold of you?"
      placeholder: ex. @octocat
    validations:
      required: false
  - type: textarea
    id: idea-details
    attributes:
      label: "What's your episode idea?"
      placeholder: Tell us what you think we should create an episode about here.
    validations:
      required: true
  - type: dropdown
    id: mobile-type
    attributes:
      label: Android or iPhone?
      options:
        - Android
        - iPhone
    validations:
      required: true
