name: Move new issues into Brainstorming

on:
  issues:
    types: [labeled]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Videos
          column: Brainstorming
          repo-token: ${{ secrets.GITHUB_TOKEN }}
